/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatBookingIdRouteImport } from './routes/chat.$bookingId'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ChatRequestRequestIdPeerIdRouteImport } from './routes/chat.request.$requestId.$peerId'
import { Route as ApiPublicHooksRequestUpdatedRouteImport } from './routes/api/public/hooks/request-updated'
import { Route as ApiPublicHooksOfferCreatedRouteImport } from './routes/api/public/hooks/offer-created'
import { Route as ApiPublicHooksNotifyRequestRouteImport } from './routes/api/public/hooks/notify-request'
import { Route as ApiPublicHooksNotifyItemRouteImport } from './routes/api/public/hooks/notify-item'
import { Route as ApiPublicHooksDailyDigestRouteImport } from './routes/api/public/hooks/daily-digest'
import { Route as ApiPublicHooksBookingPickupRouteImport } from './routes/api/public/hooks/booking-pickup'

const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatBookingIdRoute = ChatBookingIdRouteImport.update({
  id: '/chat/$bookingId',
  path: '/chat/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_authenticated/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRequestRequestIdPeerIdRoute =
  ChatRequestRequestIdPeerIdRouteImport.update({
    id: '/chat/request/$requestId/$peerId',
    path: '/chat/request/$requestId/$peerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRequestUpdatedRoute =
  ApiPublicHooksRequestUpdatedRouteImport.update({
    id: '/api/public/hooks/request-updated',
    path: '/api/public/hooks/request-updated',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksOfferCreatedRoute =
  ApiPublicHooksOfferCreatedRouteImport.update({
    id: '/api/public/hooks/offer-created',
    path: '/api/public/hooks/offer-created',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNotifyRequestRoute =
  ApiPublicHooksNotifyRequestRouteImport.update({
    id: '/api/public/hooks/notify-request',
    path: '/api/public/hooks/notify-request',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNotifyItemRoute =
  ApiPublicHooksNotifyItemRouteImport.update({
    id: '/api/public/hooks/notify-item',
    path: '/api/public/hooks/notify-item',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyDigestRoute =
  ApiPublicHooksDailyDigestRouteImport.update({
    id: '/api/public/hooks/daily-digest',
    path: '/api/public/hooks/daily-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBookingPickupRoute =
  ApiPublicHooksBookingPickupRouteImport.update({
    id: '/api/public/hooks/booking-pickup',
    path: '/api/public/hooks/booking-pickup',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/items': typeof ItemsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/requests': typeof RequestsRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/verification': typeof VerificationRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chat/$bookingId': typeof ChatBookingIdRoute
  '/api/public/hooks/booking-pickup': typeof ApiPublicHooksBookingPickupRoute
  '/api/public/hooks/daily-digest': typeof ApiPublicHooksDailyDigestRoute
  '/api/public/hooks/notify-item': typeof ApiPublicHooksNotifyItemRoute
  '/api/public/hooks/notify-request': typeof ApiPublicHooksNotifyRequestRoute
  '/api/public/hooks/offer-created': typeof ApiPublicHooksOfferCreatedRoute
  '/api/public/hooks/request-updated': typeof ApiPublicHooksRequestUpdatedRoute
  '/chat/request/$requestId/$peerId': typeof ChatRequestRequestIdPeerIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/items': typeof ItemsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/requests': typeof RequestsRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/verification': typeof VerificationRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chat/$bookingId': typeof ChatBookingIdRoute
  '/api/public/hooks/booking-pickup': typeof ApiPublicHooksBookingPickupRoute
  '/api/public/hooks/daily-digest': typeof ApiPublicHooksDailyDigestRoute
  '/api/public/hooks/notify-item': typeof ApiPublicHooksNotifyItemRoute
  '/api/public/hooks/notify-request': typeof ApiPublicHooksNotifyRequestRoute
  '/api/public/hooks/offer-created': typeof ApiPublicHooksOfferCreatedRoute
  '/api/public/hooks/request-updated': typeof ApiPublicHooksRequestUpdatedRoute
  '/chat/request/$requestId/$peerId': typeof ChatRequestRequestIdPeerIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/items': typeof ItemsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/requests': typeof RequestsRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/verification': typeof VerificationRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/chat/$bookingId': typeof ChatBookingIdRoute
  '/api/public/hooks/booking-pickup': typeof ApiPublicHooksBookingPickupRoute
  '/api/public/hooks/daily-digest': typeof ApiPublicHooksDailyDigestRoute
  '/api/public/hooks/notify-item': typeof ApiPublicHooksNotifyItemRoute
  '/api/public/hooks/notify-request': typeof ApiPublicHooksNotifyRequestRoute
  '/api/public/hooks/offer-created': typeof ApiPublicHooksOfferCreatedRoute
  '/api/public/hooks/request-updated': typeof ApiPublicHooksRequestUpdatedRoute
  '/chat/request/$requestId/$peerId': typeof ChatRequestRequestIdPeerIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/bookings'
    | '/community'
    | '/contact'
    | '/items'
    | '/privacy'
    | '/profile'
    | '/requests'
    | '/safety'
    | '/settings'
    | '/verification'
    | '/admin'
    | '/chat/$bookingId'
    | '/api/public/hooks/booking-pickup'
    | '/api/public/hooks/daily-digest'
    | '/api/public/hooks/notify-item'
    | '/api/public/hooks/notify-request'
    | '/api/public/hooks/offer-created'
    | '/api/public/hooks/request-updated'
    | '/chat/request/$requestId/$peerId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/bookings'
    | '/community'
    | '/contact'
    | '/items'
    | '/privacy'
    | '/profile'
    | '/requests'
    | '/safety'
    | '/settings'
    | '/verification'
    | '/admin'
    | '/chat/$bookingId'
    | '/api/public/hooks/booking-pickup'
    | '/api/public/hooks/daily-digest'
    | '/api/public/hooks/notify-item'
    | '/api/public/hooks/notify-request'
    | '/api/public/hooks/offer-created'
    | '/api/public/hooks/request-updated'
    | '/chat/request/$requestId/$peerId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/bookings'
    | '/community'
    | '/contact'
    | '/items'
    | '/privacy'
    | '/profile'
    | '/requests'
    | '/safety'
    | '/settings'
    | '/verification'
    | '/_authenticated/admin'
    | '/chat/$bookingId'
    | '/api/public/hooks/booking-pickup'
    | '/api/public/hooks/daily-digest'
    | '/api/public/hooks/notify-item'
    | '/api/public/hooks/notify-request'
    | '/api/public/hooks/offer-created'
    | '/api/public/hooks/request-updated'
    | '/chat/request/$requestId/$peerId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BookingsRoute: typeof BookingsRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  ItemsRoute: typeof ItemsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RequestsRoute: typeof RequestsRoute
  SafetyRoute: typeof SafetyRoute
  SettingsRoute: typeof SettingsRoute
  VerificationRoute: typeof VerificationRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  ChatBookingIdRoute: typeof ChatBookingIdRoute
  ApiPublicHooksBookingPickupRoute: typeof ApiPublicHooksBookingPickupRoute
  ApiPublicHooksDailyDigestRoute: typeof ApiPublicHooksDailyDigestRoute
  ApiPublicHooksNotifyItemRoute: typeof ApiPublicHooksNotifyItemRoute
  ApiPublicHooksNotifyRequestRoute: typeof ApiPublicHooksNotifyRequestRoute
  ApiPublicHooksOfferCreatedRoute: typeof ApiPublicHooksOfferCreatedRoute
  ApiPublicHooksRequestUpdatedRoute: typeof ApiPublicHooksRequestUpdatedRoute
  ChatRequestRequestIdPeerIdRoute: typeof ChatRequestRequestIdPeerIdRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$bookingId': {
      id: '/chat/$bookingId'
      path: '/chat/$bookingId'
      fullPath: '/chat/$bookingId'
      preLoaderRoute: typeof ChatBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/request/$requestId/$peerId': {
      id: '/chat/request/$requestId/$peerId'
      path: '/chat/request/$requestId/$peerId'
      fullPath: '/chat/request/$requestId/$peerId'
      preLoaderRoute: typeof ChatRequestRequestIdPeerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/request-updated': {
      id: '/api/public/hooks/request-updated'
      path: '/api/public/hooks/request-updated'
      fullPath: '/api/public/hooks/request-updated'
      preLoaderRoute: typeof ApiPublicHooksRequestUpdatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/offer-created': {
      id: '/api/public/hooks/offer-created'
      path: '/api/public/hooks/offer-created'
      fullPath: '/api/public/hooks/offer-created'
      preLoaderRoute: typeof ApiPublicHooksOfferCreatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notify-request': {
      id: '/api/public/hooks/notify-request'
      path: '/api/public/hooks/notify-request'
      fullPath: '/api/public/hooks/notify-request'
      preLoaderRoute: typeof ApiPublicHooksNotifyRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notify-item': {
      id: '/api/public/hooks/notify-item'
      path: '/api/public/hooks/notify-item'
      fullPath: '/api/public/hooks/notify-item'
      preLoaderRoute: typeof ApiPublicHooksNotifyItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-digest': {
      id: '/api/public/hooks/daily-digest'
      path: '/api/public/hooks/daily-digest'
      fullPath: '/api/public/hooks/daily-digest'
      preLoaderRoute: typeof ApiPublicHooksDailyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/booking-pickup': {
      id: '/api/public/hooks/booking-pickup'
      path: '/api/public/hooks/booking-pickup'
      fullPath: '/api/public/hooks/booking-pickup'
      preLoaderRoute: typeof ApiPublicHooksBookingPickupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BookingsRoute: BookingsRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  ItemsRoute: ItemsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RequestsRoute: RequestsRoute,
  SafetyRoute: SafetyRoute,
  SettingsRoute: SettingsRoute,
  VerificationRoute: VerificationRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  ChatBookingIdRoute: ChatBookingIdRoute,
  ApiPublicHooksBookingPickupRoute: ApiPublicHooksBookingPickupRoute,
  ApiPublicHooksDailyDigestRoute: ApiPublicHooksDailyDigestRoute,
  ApiPublicHooksNotifyItemRoute: ApiPublicHooksNotifyItemRoute,
  ApiPublicHooksNotifyRequestRoute: ApiPublicHooksNotifyRequestRoute,
  ApiPublicHooksOfferCreatedRoute: ApiPublicHooksOfferCreatedRoute,
  ApiPublicHooksRequestUpdatedRoute: ApiPublicHooksRequestUpdatedRoute,
  ChatRequestRequestIdPeerIdRoute: ChatRequestRequestIdPeerIdRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
